INCLUDEPATH += $$PWD

#DEFINES += SQLITE_THREADSAFE=0
DEFINES += SQLITE_DEFAULT_MEMSTATUS=0 SQLITE_DEFAULT_WAL_SYNCHRONOUS=1 SQLITE_LIKE_DOESNT_MATCH_BLOBS SQLITE_MAX_EXPR_DEPTH=0 SQLITE_OMIT_DECLTYPE SQLITE_OMIT_DEPRECATED SQLITE_OMIT_PROGRESS_CALLBACK  SQLITE_OMIT_SHARED_CACHE SQLITE_OMIT_LOAD_EXTENSION

HEADERS += \
    $$PWD/sqlite3.h \
    $$PWD/sqlite3ext.h

SOURCES += \
    $$PWD/sqlite3.c


